import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Alfa Alumínio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Essa é a Home</h1>
    </div>
  )
}
