import Head from 'next/head'
import HeroSection from '../components/Hero'
import HomeSlider from '../components/HomeSlider'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Alfa Alumínio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <HomeSlider />
      <h1>Essa é a Home bla bla bla bla</h1>
    </div>
  )
}
