import Head from 'next/head'
import AboutAlfa from '../components/About'
import Clients from '../components/ClientsSection'
import HeroSection from '../components/Hero'
import ProductSlider from '../components/ProductSlider'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Alfa Alumínio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <ProductSlider />
      <Clients />
      <AboutAlfa />
    </div>
  )
}
